import type { Metadata } from 'next';

import localFont from 'next/font/local';

import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        <div className="flex-none inset-0 pointer-events-none fixed z-10">
          <div
            style={{
              backgroundImage: "url('/background.png')",
              backgroundRepeat: 'repeat',
              backgroundSize: '109px',
              borderRadius: '0',
              height: '100%',
              opacity: '0.06',
              width: '100%',
            }}
          ></div>
        </div>
      </body>
    </html>
  );
}
